name: main-latest

on:
  push:
    branches: [ main ]

permissions: 
  packages: write
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # So git maven plugin finds all history there

      - name: Prepare
        id: prep
        run: |
          echo "::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Display info
        run: |
          echo "Date Created: ${{ steps.prep.outputs.created }}"
          echo "Current branch: ${{ steps.prep.outputs.branch_name }}"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm

      - name: Build with Maven
        run: mvn --batch-mode -Pproduction -DskipTests=true package

      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: pom

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # github username or org
          password: ${{ secrets.GITHUB_TOKEN }}    # github actions builtin token. repo has to have pkg access.

      - name: "Build and push latest & ${{ steps.pom.outputs.version }}"
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          pull: true # avoid bitrot with repeated cache hits
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/vaadin-graphql-swapi-demo:latest
            ghcr.io/${{ github.repository_owner }}/vaadin-graphql-swapi-demo:${{ steps.pom.outputs.version }}
          labels: |
            org.opencontainers.image.title=vaadin-graphql-swapi-demo
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
          cache-from: type=gha # all-automatic Github Actions caching
          cache-to: type=gha,mode=max
